### ISSUE TITLE
Unused Email field

### ISSUE THREAD

**Issue by QuentinDaveau** [med-material/ConnectToMySQL#1]
Currently, the Email input field seems to do nothing. We may want to take it into account in some way.

![image](https://user-images.githubusercontent.com/45624296/68280567-15329980-0076-11ea-8498-b18be41c1223.png)

It is good to note that, when sending logs through the ConnectToMySQL package, it is mandatory to have an "Email" entry in the logs. What could be done is that, by default, the ConnectToMySQL Email input field is used, and it can be overriden if an "Email" entry is present in the given logs.

**Comment by bastianilso** [comment]
with the new version of the logging manager, this field has been replaced by a data label field.
