### ISSUE TITLE
Move Logging scripts out of ConnectToMySQL folder

### ISSUE THREAD

**Issue by ingebronx** [med-material/ConnectToMySQL#10]
The current structure can be confusing when trying to find the scripts you want to use / edit.

**Comment by bastianilso** [comment]
I have renamed the ConnectToMySQL folder to "LoggingManager" - would that work?

**Comment by ingebronx** [comment]
Should be fine, especially if we add a guide/tutorial.

**Comment by bastianilso** [comment]
OK, I close the issue then. 👍
