### ISSUE TITLE
Loading credentials through editor breaks PHP API

### ISSUE THREAD

**Issue by bastianilso** [med-material/ConnectToMySQL#4]
Quoting quentin:

> The issue is that the newLine character stays in the strings, and this breaks the PHP API and the hashing of the DbSecKey entry. In consequence the passed credentials are invalid.
> A simple solution I found is to add a Trim() function before splitting the « = », this removes the newlines characters (string.Replace(« \n », String.Empty) doesn’t works)

We should either address this in the PHP script or from the ConnectToMySQL side.

**Comment by QuentinDaveau** [comment]
Since the ConnectToMySQL already manages the sanitizing, and this issue is due to the ConnectToMySQL package in the first place, I think this should be handled by the package.

**Comment by bastianilso** [comment]
solved with commit d198e158770133e03b8be5132b9e3917cb8cbea5
